"""
Detection pipeline.

Decides whether some content was written by a person or generated by AI.
We run a few independent signals, each returns a number in [0, 1] (1 = looks
AI-generated) or None if it can't be computed, then blend them into one
ai_probability plus a confidence score and a label to show the reader.

The signals:
  llm_judge          ask a Groq model how likely the text is AI. Best signal
                     when we have an API key; skipped if we don't.
  burstiness         humans vary sentence length a lot, AI tends to be uniform.
  lexical_diversity  type-token ratio. Repetitive vocab leans AI.
  ai_cliche          how many ChatGPT-isms show up ("delve", "tapestry", etc).
  metadata_signature only for the metadata content type. Looks for tool tags.
"""

import json
import os
import re
import statistics

GROQ_MODEL = "llama-3.3-70b-versatile"

# How much each signal counts. We renormalize over whatever is available.
TEXT_WEIGHTS = {
    "llm_judge": 0.50,
    "burstiness": 0.20,
    "lexical_diversity": 0.15,
    "ai_cliche": 0.15,
}
METADATA_WEIGHTS = {
    "llm_judge": 0.60,
    "metadata_signature": 0.40,
}

# At or above this confidence we show a "high-confidence" label.
CONFIDENCE_THRESHOLD = 0.70

# Phrases LLMs lean on. Matched case-insensitively as substrings.
AI_CLICHES = [
    "delve", "tapestry", "rich tapestry", "it's important to note",
    "it is important to note", "in conclusion", "in summary", "moreover",
    "furthermore", "navigate the complexities", "a testament to",
    "plays a crucial role", "plays a vital role", "underscore", "in today's",
    "a myriad of", "the realm of", "when it comes to", "seamless", "robust",
    "leverage", "foster", "intricate", "nuanced", "multifaceted",
    "ever-evolving", "embark", "cutting-edge", "game-changer", "elevate",
    "unlock", "vibrant", "boasts", "meticulous", "testament",
]


def _sentences(text):
    parts = re.split(r"[.!?]+", text)
    return [p.strip() for p in parts if p.strip()]


def _words(text):
    return re.findall(r"\b[\w']+\b", text.lower())


def _clamp(x, lo=0.0, hi=1.0):
    return max(lo, min(hi, x))


# Each signal_* returns (score_or_None, detail_dict).

def signal_llm_judge(text, content_type="text"):
    """Ask Groq for the probability this is AI-generated."""
    api_key = os.getenv("GROQ_API_KEY") or os.getenv("GROQ_KEY")
    if not api_key:
        return None, {"available": False, "reason": "GROQ_API_KEY not set"}

    descriptor = {
        "text": "a piece of text-based creative content",
        "image_description": "a description/caption of an image",
        "metadata": "structured metadata describing how a work was created",
    }.get(content_type, "a piece of content")

    try:
        from groq import Groq

        client = Groq(api_key=api_key)
        resp = client.chat.completions.create(
            model=GROQ_MODEL,
            temperature=0,
            response_format={"type": "json_object"},
            messages=[
                {
                    "role": "system",
                    "content": (
                        "You are an AI-content forensics expert. You assess "
                        "whether content was generated by an AI language model "
                        "or created by a human. Respond ONLY with JSON of the "
                        'form {"ai_probability": <float 0..1>, "rationale": '
                        "<short string>}. 1.0 means certainly AI-generated, "
                        "0.0 means certainly human."
                    ),
                },
                {
                    "role": "user",
                    "content": f"Assess {descriptor}:\n\n{text}",
                },
            ],
        )
        raw = resp.choices[0].message.content
        data = _extract_json(raw)
        prob = _clamp(float(data["ai_probability"]))
        return prob, {
            "available": True,
            "model": GROQ_MODEL,
            "rationale": str(data.get("rationale", ""))[:300],
        }
    except Exception as exc:
        # Anything goes wrong (no network, bad json, etc), just drop the signal.
        return None, {"available": False, "reason": f"{type(exc).__name__}: {exc}"}


def signal_burstiness(text, **_):
    """Uniform sentence lengths look more AI than varied ones."""
    sents = _sentences(text)
    if len(sents) < 2:
        return None, {"available": False, "reason": "need >= 2 sentences"}
    lengths = [len(_words(s)) for s in sents]
    mean = statistics.mean(lengths)
    if mean == 0:
        return None, {"available": False, "reason": "no words"}
    cv = statistics.pstdev(lengths) / mean
    # cv 0.7 or more reads human (0), 0.2 or less reads AI (1), linear in between.
    score = _clamp((0.7 - cv) / (0.7 - 0.2))
    return score, {
        "available": True,
        "sentence_count": len(sents),
        "coeff_of_variation": round(cv, 3),
    }


def signal_lexical_diversity(text, **_):
    """Repetitive vocabulary (low type-token ratio) leans AI."""
    words = _words(text)
    if len(words) < 15:
        return None, {"available": False, "reason": "need >= 15 words"}
    window = words[:300]  # cap so short and long texts are comparable
    ttr = len(set(window)) / len(window)
    # ttr 0.7+ reads human (0), 0.4 or less reads AI (1), linear in between.
    score = _clamp((0.7 - ttr) / (0.7 - 0.4))
    return score, {
        "available": True,
        "type_token_ratio": round(ttr, 3),
        "words_considered": len(window),
    }


def signal_ai_cliche(text, **_):
    """Count LLM stock phrases (and em dashes) per 100 words."""
    words = _words(text)
    if len(words) < 10:
        return None, {"available": False, "reason": "need >= 10 words"}
    lowered = text.lower()
    phrase_hits = sum(lowered.count(p) for p in AI_CLICHES)
    emdash_hits = text.count("—")
    hits_per_100 = (phrase_hits + 0.5 * emdash_hits) / len(words) * 100
    score = _clamp(hits_per_100 / 4.0)
    return score, {
        "available": True,
        "phrase_hits": phrase_hits,
        "em_dashes": emdash_hits,
        "tells_per_100_words": round(hits_per_100, 2),
    }


def signal_metadata_signature(text, **_):
    """For metadata: look for AI-tool tags in a JSON blob of attributes."""
    try:
        meta = json.loads(text)
        if not isinstance(meta, dict):
            raise ValueError("metadata must be a JSON object")
    except Exception as exc:
        return None, {"available": False, "reason": f"bad metadata json: {exc}"}

    ai_tools = [
        "midjourney", "dall-e", "dalle", "stable diffusion", "stablediffusion",
        "gpt", "chatgpt", "claude", "gemini", "firefly", "leonardo",
        "runway", "ai", "generative", "diffusion", "synthid",
    ]
    blob = json.dumps(meta).lower()
    tool_hits = sum(blob.count(t) for t in ai_tools)

    # Zeroed-out timestamps are a weak sign something was fabricated.
    suspicious_time = 0
    for v in meta.values():
        if isinstance(v, str) and re.search(r"00:00:00", v):
            suspicious_time += 1

    raw = 0.6 * min(tool_hits, 2) / 2 + 0.4 * min(suspicious_time, 1)
    score = _clamp(0.1 + 0.8 * raw)  # keep it off the 0 and 1 extremes
    return score, {
        "available": True,
        "ai_tool_mentions": tool_hits,
        "suspicious_timestamps": suspicious_time,
    }


SIGNAL_FUNCS = {
    "llm_judge": signal_llm_judge,
    "burstiness": signal_burstiness,
    "lexical_diversity": signal_lexical_diversity,
    "ai_cliche": signal_ai_cliche,
    "metadata_signature": signal_metadata_signature,
}


def _weights_for(content_type):
    return METADATA_WEIGHTS if content_type == "metadata" else TEXT_WEIGHTS


def run_pipeline(content, content_type="text"):
    """Run the signals, blend them, and return the full verdict dict."""
    weights = _weights_for(content_type)
    signals = []
    for name, weight in weights.items():
        score, detail = SIGNAL_FUNCS[name](content, content_type=content_type)
        signals.append(
            {
                "name": name,
                "weight": weight,
                "score": None if score is None else round(score, 3),
                "available": score is not None,
                "detail": detail,
            }
        )

    available = [s for s in signals if s["available"]]
    if not available:
        # Shouldn't really happen, but if nothing computed, call it a toss-up.
        ai_probability, confidence = 0.5, 0.0
    else:
        total_w = sum(s["weight"] for s in available)
        ai_probability = sum(s["weight"] * s["score"] for s in available) / total_w
        confidence = _compute_confidence(ai_probability, [s["score"] for s in available])

    result = "AI" if ai_probability >= 0.5 else "Human"
    label = build_label(result, confidence)
    return {
        "result": result,
        "ai_probability": round(ai_probability, 3),
        "confidence": round(confidence, 3),
        "label": label,
        "signals": signals,
    }


def _compute_confidence(ai_probability, scores):
    """How sure are we? Far from 0.5 and signals agreeing both push it up."""
    boundary_term = 2 * abs(ai_probability - 0.5)  # 0 at the boundary, 1 at the ends
    if len(scores) > 1:
        spread = statistics.pstdev(scores)  # 0 means the signals agree
        agreement_term = _clamp(1 - 2 * spread)
    else:
        agreement_term = boundary_term  # only one signal, nothing to compare
    return _clamp(0.5 * boundary_term + 0.5 * agreement_term)


def build_label(result, confidence):
    """Pick the reader-facing label. Three variants based on confidence."""
    pct = round(confidence * 100)
    if confidence >= CONFIDENCE_THRESHOLD and result == "AI":
        return (
            f"\U0001F916 Likely AI-generated. We're fairly confident this was "
            f"made with a generative AI tool ({pct}% confidence). This is an "
            f"automated guess, not proof, and the creator can appeal it."
        )
    if confidence >= CONFIDENCE_THRESHOLD and result == "Human":
        return (
            f"✍️ Likely human-written. We're fairly confident a "
            f"person wrote this ({pct}% confidence). This is an automated "
            f"guess, not proof."
        )
    return (
        f"❓ Origin unclear. We couldn't confidently tell whether a person "
        f"or an AI tool produced this ({pct}% confidence), so treat the result "
        f"as inconclusive."
    )


def _extract_json(raw):
    """Pull a JSON object out of an LLM reply even if it adds extra prose."""
    try:
        return json.loads(raw)
    except (json.JSONDecodeError, TypeError):
        match = re.search(r"\{.*\}", raw or "", re.DOTALL)
        if match:
            return json.loads(match.group(0))
        raise
